### ISSUE TITLE
emailaddress regex

### ISSUE THREAD

**Issue by MayaK06** [originaluko/haveibeenpwned#4]
very nice thank you ! - one small thing you may want to change in the regex parsing -EmailAddress is to include numbers in the email domain name - the current regex does not allow it . example @company123.com would not work.

**Comment by sid351** [comment]
There is a way to check email addresses with PowerShell that doesn't use regex.  Here are a couple of references:

https://stackoverflow.com/questions/48253743/powershell-to-validate-email-addresses

https://herringsfishbait.com/2016/07/22/powershell-check-if-an-email-address-is-valid/
